version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    # This tells RTD to install the current directory (.) 
    # It will look at your pyproject.toml automatically.
    - method: pip
      path: .
      extra_requirements:
        - docs  # Optional: only if you have a [project.optional-dependencies] section for docs
        
sphinx:
  # This is the line that was missing! 
  # Ensure the path points to your conf.py relative to the root.
  configuration: docs/conf.py